#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use \Symfony\Component\Console\Application;

$application = new Application('polite console','1.0.1');

// ... register commands
$application->addCommands(\Polite\Console\Commands::Commands());
$application->run();