#!/usr/bin/env php
<?php
// autoload
require __DIR__.'/vendor/autoload.php';

define('BASE_PATH',__DIR__);

// ... register commands
$ConsoleCommand = ConsoleCommand();
$MigrationCommand = MigrationCommand();
$command = array_merge($ConsoleCommand,$MigrationCommand);

\Polite\Console\Console::AddCommands($command);
